---
version: 1.4.10-6
default-factions-plugin: FactionsPE
enable-multiworld-chat: false
groups:
  Guest:
    chat: §f[§r{fac_name}§r] §b•§7Member§b•§9 {display_name} §7→ §f{msg}
    nametag: §l§c[§7Member§c]§r §f{display_name}
    worlds: []
  Owner:
    chat: §l§a〖§d ᴖ§6 ＯＷＮＥＲ§d ᴖ §a〗 §e{display_name} §1→§6 {msg}
    nametag: §l§a•>[-§cOwner§a-]<• §b{display_name}
    worlds: []
  OP:
    chat: §a§l[{fac_name}] §l§b•…§a✿§d❍ρ§a✿§b…• §f{display_name} §6•> §e{msg} §6<•
    nametag: §l§l§b•…§a✿§d❍ρ§a✿§b…• §f{display_name}
    worlds: []
  Co-Owner:
    nametag: '&8&l[Co-Owner]&f&r {display_name}'
    chat: '&8&l[Co-Owner]&f&r {display_name} &7> {msg}'
  Helper:
    chat: §l§a[{fac_name}] §e•…❖§aHεɭρεɾ§e❖… §f{display_name} §6•> §b{msg}
    nametag: §l§e•…❖§aHεɭρεɾ§e❖… §f{display_name}
  Member:
    chat: §a[{fac_name}] §b…•✌§a✪§fMember§a✪§b✌ §f{display_name} §6•> §f{msg}
    nametag: §l§b…•✌§a✪§fMember§a✪§b✌ §f{display_name}
  Builder:
    chat: §l§a[{fac_name}] §a…✾§9Builder§a✾… §f{display_name} §6•> §b{msg}
    nametag: §l§a…✾§9Builder§a✾… §f{display_name}
  YT:
    chat: §l§a[{fac_name}] ✌§fY❍ʊ§cζʊβℰℜ§a๖ۣۜ §f{display_name} §6•> §b{msg}
    nametag: §l✌§fY❍ʊ§cζʊβℰℜ§a๖ۣۜ §f{display_name}
  vip4:
    chat: §l§e[§r{fac_name}§r§e] §c✧ §bＶＩＰ§e☭ §bＩＶ§c ✧§6 {display_name} §a→§b {msg}
    nametag: §l•°…§b۞§eVIP-IV§b۞§a…°• §f{display_name}
  c:
    nametag: '&8&l[c]&f&r {display_name}'
    chat: '&8&l[c]&f&r {display_name} &7> {msg}'
  VIP1:
    nametag: §l§b☪ §6VIP §a☸§6 I§b ☪§d {display_name}
    chat: §l§e[§r{fac_name}§r§e] §c✧ §bＶＩＰ§e☭ §bＩ§c ✧§6 {display_name} §a→§b {msg}
  VIP2:
    chat: §l§e[§r{fac_name}§r§e] §c✧ §bＶＩＰ§e☭ §bＩＩ§c ✧§6 {display_name} §a→§b {msg}
    nametag: §l§b☪ §6VIP §a☸§6 II§b ☪§d {display_name}
  VIP3:
    chat: §l§e[§r{fac_name}§r§e] §c✧ §bＶＩＰ§e☭ §bＩＩＩ§c ✧§6 {display_name} §a→§b {msg}
    nametag: §l§b☪ §6VIP §a☸§6 III§b ☪§d {display_name}
  VIP4:
    chat: §l§e[§r{fac_name}§r§e] §c✧ §bＶＩＰ§e☭ §bＩＶ§c ✧§6 {display_name} §a→§b {msg}
    nametag: §l§b☪ §6VIP §a☸§6 IV§b ☪§d {display_name}
  VIP5:
    chat: §l§e[§r{fac_name}§r§e] §c✧ §bＶＩＰ§e☭ §bＶ§c ✧§6 {display_name} §a→§b {msg}
    nametag: §l§b☪ §6VIP §a☸§6 V§b ☪§d {display_name}
  VIP6:
    chat: §l•§b[§a{fac_name}§b]§f• §6•=-§a°§b[§eVIP-VI§b]§a°§6-=• §f{display_name}
      §6>§e {msg}§6 <
    nametag: '&8&l[VIP6]&f&r {display_name}'
  MemberS:
    chat: §b•§r{fac_name}§r§b•§e§l ♣..»§dMember§e«..♣§r§a {display_name}§c→§6 {msg}
    nametag: '&8&l[MemberS]&f&r {display_name}'
...
