---
show-messages-onjoin: true
force-hub: false
enable-hub-message: true
force-spawn: false
enable-spawn-message: true
enable-aliases: true
teleport-on-death: 1
hub-server:
  enabled: false
  name: External Server
  host: 127.0.0.1
  port: 19132
hub:
  world: island
  X: 289.396200
  "Y": 155.000000
  Z: 286.654100
  Yaw: 19.653885
  Pitch: 90.000000
...
